export enum Permission {
  PLATFORM_SETTINGS = "platform:settings",
  PLATFORM_USERS_MANAGE = "platform:users_manage",
  PLATFORM_ADMINS_MANAGE = "platform:admins_manage",

  EVENT_CREATE = "event:create",
  EVENT_READ = "event:read",
  EVENT_UPDATE = "event:update",
  EVENT_DELETE = "event:delete",
  EVENT_PUBLISH = "event:publish",
  EVENT_APPROVE = "event:approve",
  EVENT_REJECT = "event:reject",
  EVENT_FEATURE = "event:feature",

  BOOKING_CREATE = "booking:create",
  BOOKING_READ = "booking:read",
  BOOKING_CANCEL = "booking:cancel",
  BOOKING_REFUND = "booking:refund",

  STUDENT_CREATE = "student:create",
  STUDENT_READ = "student:read",
  STUDENT_UPDATE = "student:update",
  STUDENT_DELETE = "student:delete",
  STUDENT_BULK_IMPORT = "student:bulk_import",

  CERTIFICATE_GENERATE = "certificate:generate",
  CERTIFICATE_READ = "certificate:read",
  CERTIFICATE_DOWNLOAD = "certificate:download",
  CERTIFICATE_BULK_SEND = "certificate:bulk_send",

  PAYMENT_CREATE = "payment:create",
  PAYMENT_READ = "payment:read",
  PAYMENT_REFUND = "payment:refund",
  PAYOUT_APPROVE = "payout:approve",
  PAYOUT_READ = "payout:read",
  COMMISSION_READ = "commission:read",
  COMMISSION_MANAGE = "commission:manage",
  REVENUE_READ = "revenue:read",
  REVENUE_EXPORT = "revenue:export",

  COURSE_CREATE = "course:create",
  COURSE_READ = "course:read",
  COURSE_ENROLL = "course:enroll",
  GRADE_ASSIGN = "grade:assign",
  ATTENDANCE_MARK = "attendance:mark",

  INVOICE_CREATE = "invoice:create",
  INVOICE_READ = "invoice:read",
  REPORT_VIEW = "report:view",
  SETTINGS_MANAGE = "settings:manage",

  BLOG_CREATE = "blog:create",
  BLOG_READ = "blog:read",
  BLOG_UPDATE = "blog:update",
  BLOG_DELETE = "blog:delete",
  BLOG_PUBLISH = "blog:publish",
  BLOG_CATEGORIES_MANAGE = "blog:categories_manage",
  BLOG_COMMENTS_MODERATE = "blog:comments_moderate",

  MEDIA_UPLOAD = "media:upload",
  MEDIA_READ = "media:read",
  MEDIA_DELETE = "media:delete",
  BANNERS_MANAGE = "banners:manage",
  POPUPS_MANAGE = "popups:manage",
  ANNOUNCEMENTS_MANAGE = "announcements:manage",
  REELS_MANAGE = "reels:manage",
  HOMEPAGE_MANAGE = "homepage:manage",
  SEO_CONTENT_MANAGE = "seo_content:manage",

  SCHOOL_APPROVE = "school:approve",
  SCHOOL_REJECT = "school:reject",
  VENDOR_APPROVE = "vendor:approve",
  VENDOR_REJECT = "vendor:reject",

  REVIEW_MODERATE = "review:moderate",
  COMPLAINT_READ = "complaint:read",
  COMPLAINT_MANAGE = "complaint:manage",

  TICKET_READ = "ticket:read",
  TICKET_MANAGE = "ticket:manage",

  ANALYTICS_READ = "analytics:read",
  ANALYTICS_EXPORT = "analytics:export",
}
