import { UserRole } from "../../models/index";
import { Permission } from "./permissions";

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [UserRole.SUPER_ADMIN]: Object.values(Permission),
  [UserRole.ADMIN]: [
    Permission.PLATFORM_USERS_MANAGE, Permission.PLATFORM_ADMINS_MANAGE,
    Permission.EVENT_CREATE, Permission.EVENT_READ, Permission.EVENT_UPDATE, Permission.EVENT_DELETE, Permission.EVENT_PUBLISH,
    Permission.EVENT_APPROVE, Permission.EVENT_REJECT, Permission.EVENT_FEATURE,
    Permission.BOOKING_CREATE, Permission.BOOKING_READ, Permission.BOOKING_CANCEL, Permission.BOOKING_REFUND,
    Permission.STUDENT_CREATE, Permission.STUDENT_READ, Permission.STUDENT_UPDATE, Permission.STUDENT_DELETE, Permission.STUDENT_BULK_IMPORT,
    Permission.CERTIFICATE_GENERATE, Permission.CERTIFICATE_READ, Permission.CERTIFICATE_DOWNLOAD, Permission.CERTIFICATE_BULK_SEND,
    Permission.PAYMENT_CREATE, Permission.PAYMENT_READ, Permission.PAYMENT_REFUND,
    Permission.PAYOUT_APPROVE, Permission.PAYOUT_READ,
    Permission.COMMISSION_READ, Permission.COMMISSION_MANAGE,
    Permission.REVENUE_READ, Permission.REVENUE_EXPORT,
    Permission.COURSE_CREATE, Permission.COURSE_READ, Permission.COURSE_ENROLL,
    Permission.GRADE_ASSIGN, Permission.ATTENDANCE_MARK,
    Permission.INVOICE_CREATE, Permission.INVOICE_READ,
    Permission.REPORT_VIEW, Permission.SETTINGS_MANAGE,
    Permission.BLOG_CREATE, Permission.BLOG_READ, Permission.BLOG_UPDATE, Permission.BLOG_DELETE, Permission.BLOG_PUBLISH,
    Permission.BLOG_CATEGORIES_MANAGE, Permission.BLOG_COMMENTS_MODERATE,
    Permission.MEDIA_UPLOAD, Permission.MEDIA_READ, Permission.MEDIA_DELETE,
    Permission.BANNERS_MANAGE, Permission.POPUPS_MANAGE,
    Permission.ANNOUNCEMENTS_MANAGE, Permission.REELS_MANAGE,
    Permission.HOMEPAGE_MANAGE, Permission.SEO_CONTENT_MANAGE,
    Permission.SCHOOL_APPROVE, Permission.SCHOOL_REJECT,
    Permission.VENDOR_APPROVE, Permission.VENDOR_REJECT,
    Permission.REVIEW_MODERATE,
    Permission.COMPLAINT_READ, Permission.COMPLAINT_MANAGE,
    Permission.TICKET_READ, Permission.TICKET_MANAGE,
    Permission.ANALYTICS_READ, Permission.ANALYTICS_EXPORT,
  ],
  [UserRole.MODERATOR]: [
    Permission.EVENT_READ, Permission.EVENT_APPROVE, Permission.EVENT_REJECT,
    Permission.SCHOOL_APPROVE, Permission.SCHOOL_REJECT,
    Permission.VENDOR_APPROVE, Permission.VENDOR_REJECT,
    Permission.REVIEW_MODERATE,
    Permission.COMPLAINT_READ, Permission.COMPLAINT_MANAGE,
    Permission.BLOG_COMMENTS_MODERATE,
  ],
  [UserRole.BLOG_WRITER]: [
    Permission.BLOG_CREATE, Permission.BLOG_READ, Permission.BLOG_UPDATE, Permission.BLOG_DELETE, Permission.BLOG_PUBLISH,
    Permission.BLOG_CATEGORIES_MANAGE,
    Permission.BLOG_COMMENTS_MODERATE,
    Permission.SEO_CONTENT_MANAGE,
    Permission.MEDIA_UPLOAD, Permission.MEDIA_READ,
  ],
  [UserRole.SUPPORT_AGENT]: [
    Permission.TICKET_READ, Permission.TICKET_MANAGE,
    Permission.COMPLAINT_READ, Permission.COMPLAINT_MANAGE,
    Permission.STUDENT_READ,
    Permission.BOOKING_READ,
    Permission.EVENT_READ,
  ],
  [UserRole.CONTENT_MANAGER]: [
    Permission.BANNERS_MANAGE, Permission.POPUPS_MANAGE,
    Permission.ANNOUNCEMENTS_MANAGE, Permission.REELS_MANAGE,
    Permission.HOMEPAGE_MANAGE,
    Permission.MEDIA_UPLOAD, Permission.MEDIA_READ, Permission.MEDIA_DELETE,
    Permission.BLOG_READ,
  ],
  [UserRole.FINANCE_MANAGER]: [
    Permission.PAYOUT_READ, Permission.PAYOUT_APPROVE,
    Permission.COMMISSION_READ, Permission.COMMISSION_MANAGE,
    Permission.REVENUE_READ, Permission.REVENUE_EXPORT,
    Permission.PAYMENT_READ, Permission.PAYMENT_REFUND,
    Permission.ANALYTICS_READ, Permission.ANALYTICS_EXPORT,
    Permission.REPORT_VIEW,
  ],
  [UserRole.VENDOR]: [
    Permission.EVENT_CREATE, Permission.EVENT_READ, Permission.EVENT_UPDATE, Permission.EVENT_DELETE, Permission.EVENT_PUBLISH,
    Permission.BOOKING_READ, Permission.BOOKING_CANCEL,
    Permission.PAYMENT_READ,
    Permission.STUDENT_READ,
    Permission.CERTIFICATE_GENERATE, Permission.CERTIFICATE_READ, Permission.CERTIFICATE_BULK_SEND,
    Permission.ANALYTICS_READ,
  ],
  [UserRole.SCHOOL]: [
    Permission.EVENT_CREATE, Permission.EVENT_READ, Permission.EVENT_UPDATE,
    Permission.STUDENT_CREATE, Permission.STUDENT_READ, Permission.STUDENT_UPDATE, Permission.STUDENT_BULK_IMPORT,
    Permission.CERTIFICATE_GENERATE, Permission.CERTIFICATE_READ, Permission.CERTIFICATE_BULK_SEND,
    Permission.REPORT_VIEW,
    Permission.COURSE_CREATE, Permission.COURSE_READ,
  ],
  [UserRole.TEACHER]: [
    Permission.EVENT_CREATE, Permission.EVENT_READ, Permission.EVENT_UPDATE,
    Permission.STUDENT_READ,
    Permission.CERTIFICATE_GENERATE, Permission.CERTIFICATE_READ,
    Permission.COURSE_CREATE, Permission.COURSE_READ,
    Permission.ATTENDANCE_MARK, Permission.GRADE_ASSIGN,
  ],
  [UserRole.EMPLOYEE]: [
    Permission.EVENT_READ,
    Permission.BOOKING_READ,
    Permission.STUDENT_READ,
  ],
  [UserRole.STUDENT]: [
    Permission.EVENT_READ,
    Permission.BOOKING_READ,
    Permission.CERTIFICATE_READ, Permission.CERTIFICATE_DOWNLOAD,
    Permission.COURSE_READ,
  ],
  [UserRole.PARENT]: [
    Permission.EVENT_READ,
    Permission.BOOKING_CREATE, Permission.BOOKING_READ, Permission.BOOKING_CANCEL,
    Permission.STUDENT_READ,
    Permission.CERTIFICATE_READ, Permission.CERTIFICATE_DOWNLOAD,
    Permission.PAYMENT_CREATE, Permission.PAYMENT_READ,
  ],
  [UserRole.CUSTOMER]: [
    Permission.EVENT_READ,
    Permission.BOOKING_CREATE, Permission.BOOKING_READ, Permission.BOOKING_CANCEL,
    Permission.CERTIFICATE_READ, Permission.CERTIFICATE_DOWNLOAD,
  ],
};
