/**
 * Generic report PDF renderer.
 *
 * Launches a headless Puppeteer browser, renders the provided HTML string,
 * and outputs an A4 portrait PDF buffer with page numbers in the footer.
 *
 * The HTML must be self-contained (inline <style> only, no external CSS or
 * remote fonts that could cause Puppeteer to hang).
 *
 * The certificate worker keeps its own htmlToPdf — this util is independent
 * so changes here cannot break certificate generation.
 */

/**
 * Render a self-contained HTML string to an A4 portrait PDF.
 *
 * Retries once on transient Puppeteer connection errors.
 *
 * @param html - Full HTML document string (must include <html>, <head>, <body>)
 * @returns PDF as a Buffer
 */
export async function renderReportPdf(html: string): Promise<Buffer> {
  const renderOnce = async (): Promise<Buffer> => {
    // Dynamic import keeps the module lazy — only loads Puppeteer when actually needed.
    const puppeteer = await import("puppeteer");
    const browser = await puppeteer.default.launch({
      args: [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu",
      ],
      headless: true,
    });

    let page: any = null;
    try {
      page = await browser.newPage();

      // domcontentloaded avoids hanging on slow/external image loads
      await page.setContent(html, { waitUntil: "domcontentloaded", timeout: 30_000 });

      // Wait for all <img> elements to fully load (or error) before capturing
      await page.evaluate(() =>
        Promise.all(
          Array.from(document.images)
            .filter((img: any) => !img.complete)
            .map(
              (img: any) =>
                new Promise<void>((resolve) => {
                  img.onload = img.onerror = () => resolve();
                }),
            ),
        ),
      );

      const pdfBuffer = await page.pdf({
        format: "A4",
        printBackground: true,
        margin: { top: "16mm", right: "12mm", bottom: "20mm", left: "12mm" },
        displayHeaderFooter: true,
        // Puppeteer requires a non-empty headerTemplate even when unused
        headerTemplate: "<div></div>",
        footerTemplate: `
          <div style="font-size:9px;color:#999;width:100%;text-align:center;padding:0 12mm;font-family:sans-serif;">
            Page <span class="pageNumber"></span> of <span class="totalPages"></span>
            &nbsp;&mdash;&nbsp; Generated by GEMA Admin
          </div>`,
      });

      return Buffer.from(pdfBuffer);
    } finally {
      if (page) await page.close().catch(() => {});
      await browser.close().catch(() => {});
    }
  };

  try {
    return await renderOnce();
  } catch (error: any) {
    const message = error?.message || String(error ?? "");
    // Retry once on transient Puppeteer connection failures
    if (
      /connection closed|page has been closed|target closed|protocol error/i.test(message)
    ) {
      return await renderOnce();
    }
    throw error;
  }
}
